# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'EyelidDivination-ios' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for EyelidDivination-ios

  target 'EyelidDivination-iosTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'EyelidDivination-iosUITests' do
    # Pods for testing
  end
  pod 'Firebase'
pod 'Firebase/Auth'
 pod 'RxSwift', '~> 5'
 pod 'RxCocoa', '~> 5'
pod 'RxSwiftExt', '~> 5'
end
